# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(252224)
$foreground = rgb(FDE8B6)
$color0 = rgb(4B484A)
$color1 = rgb(27181F)
$color2 = rgb(63233C)
$color3 = rgb(722643)
$color4 = rgb(B53886)
$color5 = rgb(B86558)
$color6 = rgb(BA8D22)
$color7 = rgb(F3D58E)
$color8 = rgb(AA9563)
$color9 = rgb(342029)
$color10 = rgb(842E4F)
$color11 = rgb(983259)
$color12 = rgb(F24BB2)
$color13 = rgb(F68775)
$color14 = rgb(F8BC2E)
$color15 = rgb(F3D58E)
