-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */
-- Decoration Settings

-- Hyprland Wiki Links
-- Animation - https://wiki.hyprland.org/Configuring/Animations/
-- Decoration - https://wiki.hyprland.org/Configuring/Variables/#decoration

-- Load colors generated by wallust
local wallustConf = os.getenv("HOME") .. "/.config/hypr/wallust/wallust-hyprland.conf"
local colors = {}
local f = io.open(wallustConf, "r")
if f then
  for line in f:lines() do
    local key, value = line:match("^%$(%w+)%s*=%s*(.+)$")
    if key and value then
      colors[key] = value:gsub("%s+$", "")
    end
  end
  f:close()
end

hl.config({
  general = {
    border_size               = 2,
    gaps_in                   = 2,
    gaps_out                  = 4,
    ["col.active_border"]     = "rgb(F24BB2)",
    ["col.inactive_border"]   = "rgb(842E4F)",
  },

  decoration = {
    rounding            = 0,
    active_opacity      = 1.0,
    inactive_opacity    = 0.9,
    fullscreen_opacity  = 1.0,
    dim_inactive        = true,
    dim_strength        = 0.04,
    dim_special         = 0.1,

    shadow = {
      enabled       = true,
      range         = 3,
      render_power  = 1,
      color         = "rgb(F24BB2)",
      color_inactive = "rgb(842E4F)",
    },

    blur = {
      enabled           = true,
      size              = 6,
      passes            = 3,
      new_optimizations = true,
      xray              = true,
      ignore_opacity    = true,
      special           = true,
      popups            = true,
    },
  },

  group = {
    ["col.border_active"] = "rgb(F3D58E)",

    groupbar = {
      ["col.active"] = "rgb(4B484A)",
    },
  },
})
