# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules
# This file will not be modified during dotfiles updates

windowrule {
    name = batteryZenWindowrule
    center = on
    match:class = ^(battery-zen)$
    float = on
    size = monitor_w*0.90 monitor_h*0.90
}

windowrule {
    name = alacrittyWindowrule
    workspace = 1
    match:class = Alacritty
}

windowrule {
    name = vscWindowrule
    workspace = 2
    match:class = code
}

windowrule {
    name = novelWriterWindowrule
    workspace = 2
    match:class = novelWriter
}

windowrule {
    name = vivaldiWindowrule
    workspace = 3
    match:class = vivaldi-stable
}

windowrule {
    name = librewolfWindowrule
    workspace = 3
    match:class = librewolf
}

windowrule {
    name = elementWindowrule
    workspace = 4
    match:class = Element
}

windowrule {
    name = feh
    float = on
    match:class = feh
}

windowrule {
    name = joplinWindowrule
    workspace = 4
    match:class = @joplin/app-desktop
}

windowrule {
  name = feh
  float = on
  match:class = feh
}

windowrule {
  name = vscWindowrule
  workspace = 2
  match:class = code
}

windowrule {
  name = novelWriterWindowrule
  workspace = 2
  match:class = novelWriter
}

windowrule {
  name = vivaldiWindowrule
  workspace = 3
  match:class = vivaldi-stable
}

windowrule {
  name = librewolfWindowrule
  workspace = 3
  match:class = librewolf
}

windowrule {
  name = elementWindowrule
  workspace = 4
  match:class = Element
}

windowrule {
  name = joplinWindowrule
  workspace = 4
  match:class = @joplin/app-desktop
}

windowrule {
  name = musicControllerWindowrule
  center = on
  float = on
  tile = off
  size = (monitor_w*0.45) (monitor_h*0.45)
  stay_focused = on
  match:class = ^(music-controller)$
}

windowrule {
  name = desktopPortalWindowrule
  center = on
  float = on
  tile = off
  size = (monitor_w*0.33) (monitor_h*0.33)
  stay_focused = on
  match:class = ^(xdg-desktop-portal-gtk)$
}

# fzf-clip script
windowrule {
  name = fzfclipWindowRule
  size = (monitor_w*0.65) (monitor_h*0.65)
  float = on
  pin = on
  match:class = ^(fzf-clip)$
  group = off
}

# fzf-clip script
windowrule {
  name = gimp
  size = (monitor_w*0.9) (monitor_h*0.9)
  float = on
  match:class = ^(gimp)$
  group = off
}

# fzf-clip script
windowrule {
  name = gimpExport
  size = (monitor_w*0.5) (monitor_h*0.5)
  float = on
  match:class = ^(^file-[a-zA-Z0-9]+$)
  group = off
}
